/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddElementModal: typeof import('./src/components/add-element-modal.vue')['default']
    AddNodeModal: typeof import('./src/components/add-node-modal.vue')['default']
    NodeInfoModal: typeof import('./src/components/node-info-modal.vue')['default']
  }
}
